# Generated by Django 4.0.6 on 2022-07-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tech Stacks',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, null=True)),
                ('description', models.TextField(null=True)),
                ('featured', models.CharField(max_length=400, null=True)),
                ('image', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('link_to_live_version', models.URLField(blank=True, null=True)),
                ('link_to_dource', models.URLField(blank=True, null=True)),
                ('techonologies', models.ManyToManyField(to='api.technologies')),
            ],
            options={
                'verbose_name_plural': 'Projects list',
            },
        ),
    ]
