# Generated by Django 4.0.6 on 2022-07-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='link_to_dource',
            new_name='link_to_source',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='techonologies',
            new_name='technologies',
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
